apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-devops-nodejs-config
  namespace: devsu
  labels:
    app.kubernetes.io/name: demo-devops-nodejs
data:
  # Non-sensitive application configuration
  PORT: "8000"
  DATABASE_NAME: "/data/dev.sqlite"
