apiVersion: v2
name: demo-devops-nodejs
description: Helm chart for the users REST API (Devsu DevOps technical test)
type: application
version: 0.1.0
appVersion: "1.0.0"
maintainers:
  - name: gpleyton
sources:
  - https://github.com/gpleyton/gpleyton_devsu
